version: '3.6'
services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
#      - MYSQL_DATABASE=Myroslav
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:

networks:
  projector_network:
    driver: bridge
